#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
advanced_features.py — Extra Enterprise Modules (Remediation, RBAC, Multi-SIEM)
"""

import requests
import logging
from typing import Dict, Any, List

logger = logging.getLogger(__name__)

# 1. Multi-SIEM Webhook Connectors (Slack, Teams, Discord)
def send_multi_siem_alert(channels: Dict[str, str], title: str, message: str, severity: str = "INFO") -> Dict[str, bool]:
    """Sends alerts to multiple platforms simultaneously (Discord, Slack, MS Teams)."""
    results = {}
    
    # Discord
    if channels.get("discord"):
        try:
            payload = {"embeds": [{"title": title, "description": message, "color": 15158332}]}
            resp = requests.post(channels["discord"], json=payload, timeout=5)
            results["discord"] = resp.status_code in [200, 204]
        except Exception:
            results["discord"] = False

    # Slack Webhook
    if channels.get("slack"):
        try:
            payload = {"text": f"*{title}*\n{message}"}
            resp = requests.post(channels["slack"], json=payload, timeout=5)
            results["slack"] = resp.status_code == 200
        except Exception:
            results["slack"] = False

    # Microsoft Teams Webhook
    if channels.get("teams"):
        try:
            payload = {"title": title, "text": message}
            resp = requests.post(channels["teams"], json=payload, timeout=5)
            results["teams"] = resp.status_code in [200, 201]
        except Exception:
            results["teams"] = False

    return results


# 2. Automated Remediation Script Generator
def generate_remediation_script(infra: Dict[str, Any], recon: Dict[str, Any]) -> str:
    """Generates automated bash hardening script based on live scan findings."""
    lines = [
        "#!/usr/bin/env bash",
        "# Automated Hardening & Remediation Script generated by MHZALY Platform",
        "echo '[*] Starting security patch application...'",
        ""
    ]
    
    headers = infra.get('headers', {})
    missing_headers = [h for h, val in headers.items() if val == 'MISSING']
    if missing_headers:
        lines.append("echo '[+] Enforcing missing security headers in Web Server configuration...'")
        for h in missing_headers:
            lines.append(f"echo 'add_header {h} \"nosniff\" always;' >> /etc/nginx/security_headers.conf")

    exposed = recon.get('exposed_files', [])
    if exposed:
        lines.append("echo '[+] Restricting access to exposed sensitive endpoints...'")
        for e in exposed:
            lines.append(f"# Found exposed: {e.get('path')}")
            lines.append(f"# Recommended fix: Restrict file permissions or add auth guard.")

    lines.append("echo '[+] Hardening script execution completed successfully.'")
    return "\n".join(lines)


# 3. Role-Based Access Control (RBAC) Checker
def check_operator_permissions(role: str, required_role: str) -> bool:
    """Validates if the operator role has sufficient privileges."""
    hierarchy = {"Viewer": 1, "Blue Team SOC Analyst": 2, "Red Team Operator": 3, "Administrator": 4}
    return hierarchy.get(role, 1) >= hierarchy.get(required_role, 1)
